/**
 * Catalogue scraped from the three bdmushroom.com/shop pages.
 *
 * `name`, `category`, `retailLow` and `retailHigh` are the site's own
 * values. `cost` is NOT from the site — the shop only publishes retail
 * prices — so it is an estimate at 60% of the lowest listed price, and
 * `stock` is invented. Both are there to make the dashboard meaningful;
 * edit them to your real numbers.
 */
export type CatalogueItem = {
  name: string;
  category: string;
  cost: number;
  retailLow: number;
  retailHigh: number;
  stock: number;
  details: string;
};

export const CATALOGUE: CatalogueItem[] = [
  {
    name: "তাজা বোতাম মাশরুম / Fresh Button Mushroom",
    category: "Button Mushroom",
    cost: 460,
    retailLow: 770,
    retailHigh: 1600,
    stock: 8,
    details: "Listed ৳770–৳1,600 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "বাটন মাশরুমের আচার / Button Mushroom Pickles",
    category: "Button Mushroom",
    cost: 360,
    retailLow: 600,
    retailHigh: 800,
    stock: 20,
    details: "Listed ৳600–৳800 on bdmushroom.com. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "শুঁকন গণোডার্মা মাশরুম / Dry Ganoderma Mushroom",
    category: "Consumer Products",
    cost: 660,
    retailLow: 1100,
    retailHigh: 5000,
    stock: 18,
    details: "Listed ৳1,100–৳5,000 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "শুকন বাটন মাশরুম / Dry Button Mushroom",
    category: "Dried Mushroom",
    cost: 840,
    retailLow: 1400,
    retailHigh: 6500,
    stock: 6,
    details: "Listed ৳1,400–৳6,500 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "শুকনো ঝিনুক মাশরুম / Dry Oyster Mushroom.",
    category: "Dried Mushroom",
    cost: 310,
    retailLow: 520,
    retailHigh: 2600,
    stock: 16,
    details: "Listed ৳520–৳2,600 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "Pressure Release Valve Manual",
    category: "Farmer Products",
    cost: 360,
    retailLow: 600,
    retailHigh: 2000,
    stock: 6,
    details: "Listed ৳600–৳2,000 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "এগার এগার পাউডার/Agar Agar Powder",
    category: "Farmer Products",
    cost: 300,
    retailLow: 500,
    retailHigh: 4200,
    stock: 20,
    details: "Listed ৳500–৳4,200 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "এল-অ্যাসপারাগিন/L-Asparagine",
    category: "Farmer Products",
    cost: 1260,
    retailLow: 2100,
    retailHigh: 7500,
    stock: 7,
    details: "Listed ৳2,100–৳7,500 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "ডেক্সট্রোজ পাউডার/Dextrose Powder",
    category: "Farmer Products",
    cost: 330,
    retailLow: 550,
    retailHigh: 2200,
    stock: 15,
    details: "Listed ৳550–৳2,200 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "12v DC Motor / ১২ ভোল্ট ডিসি মটর",
    category: "Farming Equipment",
    cost: 390,
    retailLow: 650,
    retailHigh: 1200,
    stock: 20,
    details: "Listed ৳650–৳1,200 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "Auto Fogger / অটো ফগার",
    category: "Farming Equipment",
    cost: 40,
    retailLow: 65,
    retailHigh: 250,
    stock: 48,
    details: "Listed ৳65–৳250 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "Autoclave Machine/অটোক্লেভ মেশিন",
    category: "Farming Equipment",
    cost: 19200,
    retailLow: 32000,
    retailHigh: 38000,
    stock: 2,
    details: "Listed ৳32,000–৳38,000 on bdmushroom.com. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "Coco Coir Peat / কোকো কয়ার পিট",
    category: "Farming Equipment",
    cost: 180,
    retailLow: 300,
    retailHigh: 400,
    stock: 47,
    details: "Listed ৳300–৳400 on bdmushroom.com. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "Digital Thermometer/ডিজিটাল থার্মোমিটার",
    category: "Farming Equipment",
    cost: 270,
    retailLow: 450,
    retailHigh: 600,
    stock: 21,
    details: "Listed ৳450–৳600 on bdmushroom.com. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "Digital Weight Scale/ডিজিটাল ওজন স্কেল",
    category: "Farming Equipment",
    cost: 290,
    retailLow: 480,
    retailHigh: 2800,
    stock: 78,
    details: "Listed ৳480–৳2,800 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "Glue Tape/আঠালো টেপ",
    category: "Farming Equipment",
    cost: 15,
    retailLow: 25,
    retailHigh: 45,
    stock: 30,
    details: "Listed ৳25–৳45 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "Hand Gun Spray / হ্যান্ড গান স্প্রে",
    category: "Farming Equipment",
    cost: 270,
    retailLow: 450,
    retailHigh: 550,
    stock: 74,
    details: "Listed ৳450–৳550 on bdmushroom.com. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "Hand Spray/হাত স্প্রে",
    category: "Farming Equipment",
    cost: 15,
    retailLow: 25,
    retailHigh: 40,
    stock: 63,
    details: "Listed ৳25–৳40 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "Hygrometer / হাইড্রোমিটার",
    category: "Farming Equipment",
    cost: 310,
    retailLow: 520,
    retailHigh: 650,
    stock: 11,
    details: "Listed ৳520–৳650 on bdmushroom.com. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "Infrared Thermal Meter/ইনফ্রারেড তাপ মিটার",
    category: "Farming Equipment",
    cost: 540,
    retailLow: 900,
    retailHigh: 1200,
    stock: 12,
    details: "Listed ৳900–৳1,200 on bdmushroom.com. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "Iron Drum/আয়রন ড্রাম",
    category: "Farming Equipment",
    cost: 780,
    retailLow: 1300,
    retailHigh: 1500,
    stock: 16,
    details: "Listed ৳1,300–৳1,500 on bdmushroom.com. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "Jute Rope/পাটের দড়ি",
    category: "Farming Equipment",
    cost: 70,
    retailLow: 120,
    retailHigh: 150,
    stock: 75,
    details: "Listed ৳120–৳150 on bdmushroom.com. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "MOTHER SPON / মাদার বীজ",
    category: "Farming Equipment",
    cost: 900,
    retailLow: 1500,
    retailHigh: 1800,
    stock: 11,
    details: "Listed ৳1,500–৳1,800 on bdmushroom.com. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "Neck & Cap / নেক ও কেপ",
    category: "Farming Equipment",
    cost: 2,
    retailLow: 3,
    retailHigh: 6,
    stock: 64,
    details: "Listed ৳3–৳6 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "Plastic Drum/প্লাস্টিকের ড্রাম",
    category: "Farming Equipment",
    cost: 1020,
    retailLow: 1700,
    retailHigh: 1900,
    stock: 8,
    details: "Listed ৳1,700–৳1,900 on bdmushroom.com. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "Polypropylene (p p) / পলিপ্রোপেইন (পি পি)",
    category: "Farming Equipment",
    cost: 170,
    retailLow: 280,
    retailHigh: 300,
    stock: 29,
    details: "Listed ৳280–৳300 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "Pressure Release Valve Auto",
    category: "Farming Equipment",
    cost: 300,
    retailLow: 500,
    retailHigh: 650,
    stock: 7,
    details: "Listed ৳500–৳650 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "Straw cutter / খড় কাটার",
    category: "Farming Equipment",
    cost: 11400,
    retailLow: 19000,
    retailHigh: 24000,
    stock: 0,
    details: "Listed ৳19,000–৳24,000 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "Water Sprayer/পানি স্প্রেয়ার",
    category: "Farming Equipment",
    cost: 540,
    retailLow: 900,
    retailHigh: 1600,
    stock: 9,
    details: "Listed ৳900–৳1,600 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "ইউভি লাইট / UV Light",
    category: "Farming Equipment",
    cost: 1080,
    retailLow: 1800,
    retailHigh: 2500,
    stock: 15,
    details: "Listed ৳1,800–৳2,500 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "ক্যালসিয়াম সালফাইড/Calcium Sulfide",
    category: "Farming Equipment",
    cost: 180,
    retailLow: 300,
    retailHigh: 500,
    stock: 55,
    details: "Listed ৳300–৳500 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "চাপ মিটার / Pressure Meter",
    category: "Farming Equipment",
    cost: 300,
    retailLow: 500,
    retailHigh: 600,
    stock: 6,
    details: "Listed ৳500–৳600 on bdmushroom.com. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "তাপ মিটার / Temperature Meter",
    category: "Farming Equipment",
    cost: 1080,
    retailLow: 1800,
    retailHigh: 2000,
    stock: 5,
    details: "Listed ৳1,800–৳2,000 on bdmushroom.com. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "রাবার বেন/Rubber Bean",
    category: "Farming Equipment",
    cost: 25,
    retailLow: 45,
    retailHigh: 400,
    stock: 49,
    details: "Listed ৳45–৳400 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "ল্যাম্প / Lamp",
    category: "Farming Equipment",
    cost: 110,
    retailLow: 180,
    retailHigh: 250,
    stock: 56,
    details: "Listed ৳180–৳250 on bdmushroom.com. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "হিটার কয়েল/Heater Coil",
    category: "Farming Equipment",
    cost: 660,
    retailLow: 1100,
    retailHigh: 2600,
    stock: 20,
    details: "Listed ৳1,100–৳2,600 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "Milky Mushroom/মিল্কি মাশরুম",
    category: "Fresh Mushroom",
    cost: 600,
    retailLow: 1000,
    retailHigh: 1200,
    stock: 12,
    details: "Listed ৳1,000–৳1,200 on bdmushroom.com. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "গুড়া ঝিনুক মাশরুম / Powder Oyster Mushroom",
    category: "Fresh Mushroom",
    cost: 360,
    retailLow: 600,
    retailHigh: 3000,
    stock: 14,
    details: "Listed ৳600–৳3,000 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "তাজা ঝিনুক মাশরুম / Fresh Oyster Mushroom",
    category: "Fresh Mushroom",
    cost: 300,
    retailLow: 500,
    retailHigh: 580,
    stock: 19,
    details: "Listed ৳500–৳580 on bdmushroom.com. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "Lab Spoon / ল্যাব চামচ",
    category: "Lab Instrument",
    cost: 70,
    retailLow: 120,
    retailHigh: 150,
    stock: 49,
    details: "Listed ৳120–৳150 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "ইথানল/Ethanol",
    category: "Lab Instrument",
    cost: 1320,
    retailLow: 2200,
    retailHigh: 4500,
    stock: 5,
    details: "Listed ৳2,200–৳4,500 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "টেস্ট টিউব/Test Tube",
    category: "Lab Instrument",
    cost: 8,
    retailLow: 14,
    retailHigh: 39,
    stock: 39,
    details: "Listed ৳14–৳39 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "মোচাকার বোতল / Conical Flask",
    category: "Lab Instrument",
    cost: 180,
    retailLow: 300,
    retailHigh: 900,
    stock: 45,
    details: "Listed ৳300–৳900 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "স্প্রিট/Spirit",
    category: "Lab Instrument",
    cost: 210,
    retailLow: 350,
    retailHigh: 400,
    stock: 57,
    details: "Listed ৳350–৳400 on bdmushroom.com. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "গুঁড়া গণোডার্মা মাশরুম / Powder Ganoderma Mushroom",
    category: "Mushroom Products",
    cost: 240,
    retailLow: 400,
    retailHigh: 3600,
    stock: 63,
    details: "Listed ৳400–৳3,600 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
  {
    name: "ঝিনুক মাশরুম আচার | Oyster Mushroom Pickle",
    category: "Oyster Mushroom",
    cost: 95,
    retailLow: 160,
    retailHigh: 410,
    stock: 22,
    details: "Listed ৳160–৳410 on bdmushroom.com. Variable product. Cost price is an estimate — edit it to your real buy price.",
  },
];
